name: OpenTofu CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: OpenTofu Lint & Validate
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.user.login == 'quiquecmtt'
      )
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@000eeb8522f0572907c393e8151076c205fdba1b # v1

      - name: OpenTofu Format Check
        run: tofu fmt -check -recursive

      - name: OpenTofu Init
        run: tofu init -backend=false

      - name: OpenTofu Validate
        run: tofu validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v6

      - name: Run TFLint
        run: tflint --recursive
